routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/about-us', 'HomeController@about');
Route::get('/facilities', 'HomeController@facilities');
Route::get('/blogs','HomeController@blog');
Route::get('/contact','HomeController@contact');
Route::get('/albums/{slug}', 'HomeController@albumImages');

Route::get('/albums', 'HomeController@albums');
Route::get('/albums/{slug}', 'HomeController@albumImages');




Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('optimize');

app/Album.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Album extends Model
{
    public function album_images()
    {
        return $this->hasMany('App\Gallery');
    }
}

app/Http/Controllers/Admin/AlbumController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Album;
use App\Gallery;
use Auth;

class AlbumController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(Request $request)
    {
        $this->middleware('auth:admin_user');
    }

    public function index()
    {
        $albums = Album::orderBy('year','desc')->orderBy('created_at','desc')->get();
        return view('admin.albums.index')->with('albums',$albums);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(array(
            'name'=>'required|max:191',
            'year'=> 'required'
        ),array(
            'name.required' => 'Album name is required',
            'year.required' => 'ALbum year is required'
        ));

        $i = 1;
        $name = $request->name;
        while(Album::where('name', $name)->where('year', $request->year)->exists()){
            $name = $request->name. '('.$i.')';
            $i++;
        }
        
        $slug = str_replace(' ','-',strtolower($name));
        $album = new Album;
        $album->name = $name;
        $album->year = $request->year;
        $album->slug = $slug.'-'.$request->year;

        $album->save();

        $request->session()->flash('success', 'New album created');

        return redirect()->route('albums.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $album = Album::find($id);
        if(!$album)
            abort(404);

        return view('admin.albums.show')->with('album',$album);
    }

    public function addImages($id,Request $request){
        $album = Album::find($id);
        if(!$album) abort(404);
        
        if($request->hasFile('files')){
            $images = $request->file('files');  
        }

        $count = 0;
        foreach($images as $image){
            $gallery = new Gallery;
            $filename = time().'G'.$count++ . '.' . $image->getClientOriginalExtension();
            $location = public_path('gallery/');
            $image->move($location,$filename);
            $gallery->image = $filename;
            $gallery->album_id = $id;
            $gallery->save();
        }
        
        $request->session()->flash('success', 'Images Uploaded');
        return;
    }

    public function deleteImage($album_id, $image_id,Request $request)
    {
        $gallery = Gallery::find($image_id);
        if(!$gallery) abort(404);

        unlink(public_path('gallery/'.$gallery->image));
        $gallery->delete();

        $request->session()->flash('success', 'Image Deleted');
        return redirect()->route('albums.show',$album_id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate(array(
            'editname'=>'required|max:191',
            'edityear'=> 'required'
        ),array(
            'editname.required' => 'Album name is required',
            'edityear.required' => 'ALbum year is required'
        ));
        
        $i = 1;
        $name = $request->editname;
        $album = Album::find($id);
        if(!$album) abort(404);

        if($name != $album->name){
            while(Album::where('name', $name)->where('year', $request->edityear)->exists()){
                $name = $request->editname. '('.$i.')';
                $i++;
            }
        }
        
        $slug = str_replace(' ','-',strtolower($name));
        
        $album->name = $name;
        $album->year = $request->edityear;
        $album->slug = $slug.'-'.$request->edityear;
        $album->save();

        $request->session()->flash('success', 'Album upated');

        return redirect()->route('albums.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,Request $request)
    {
        $album = Album::find($id);
        if(!$album) abort(404);

        foreach($album->album_images as $image){
            unlink(public_path('gallery/'.$image->image));
        }
        $album->delete();

        $request->session()->flash('success', 'Album deleted');

        return redirect()->route('albums.index');
    }
}

resources/views/admin/albums/index.blade.php
 @extends('layouts.admin')

 @section('body')
    @if (count($errors)>0 )
        <div class="alert alert-dismissible fade in mb-2">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true" style="color:black">&times;</span>
            </button>
            <ul class="list-group">
                @foreach ($errors->all() as $error)
                <li class="list-group-item list-group-item-danger">{{ $error }}</li>
                @endforeach
            </ul>
        </div>	
    @endif
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Albums</h2>
        </div>
        <div class="text-xs-right">
            <button class="btn btn-primary btn-min-width mr-2 mb-1" data-toggle="modal" data-target="#addAlbum">Add new Album</button>
        </div>
    </div>
    <div class="content-body">
        
        <div class="card">
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <div class="row">

                        @foreach($albums as $album)
                            <div class="col-xl-3 col-md-6 col-sm-12 " style="margin-bottom:10px">
                                <?php $images = $album->album_images()->limit(3)->get(); ?>
                                <a href="{{ route('albums.show',$album->id) }}">
                                    @if(count($images)>0)
                                        <div id="carousel-wrap{{$album->id}}" class="carousel slide" data-ride="carousel" data-wrap="false" style="height:200px;width:200px">
                                            <ol class="carousel-indicators">
                                                @foreach($images as $i)
                                                    <li data-target="#carousel-wrap{{$album->id}}" data-slide-to="{{$loop->iteration-1}}" class="{{$loop->iteration==1?'active':''}}"></li>
                                                @endforeach
                                            </ol>
                                            <div class="carousel-inner" role="listbox">
                                                @foreach($images as $i)
                                                    <div class="carousel-item {{$loop->iteration==1?'active':''}}">
                                                        <img src="{{ route('optimize', ['gallery',$i->image,200,200]) }}" alt="{{$loop->iteration}} slide">
                                                    </div>
                                                @endforeach
                                            </div>
                                            <a class="left carousel-control" href="#carousel-wrap{{$album->id}}" role="button" data-slide="prev">
                                                <span class="icon-prev" aria-hidden="true"></span>
                                                <span class="sr-only">Previous</span>
                                            </a>
                                            <a class="right carousel-control" href="#carousel-wrap{{$album->id}}" role="button" data-slide="next">
                                                <span class="icon-next" aria-hidden="true"></span>
                                                <span class="sr-only">Next</span>
                                            </a>
                                        </div>
                                    @else
                                        <img src="/img/gallery.jpg" style="height:200px;width:200px"/><br>
                                    @endif
                                </a><br>
                                <a href="{{ route('albums.show',$album->id) }}"><h4 class="card-title ">{{ $album->name }} - {{ $album->year }}</h4></a>

                                <a class="btn btn-outline-warning" onclick="editAlbum({{ $album }})"><i class="icon-edit"></i></a>
                            
                                <form action="{{ route('albums.destroy',$album->id) }}" method="POST" style="display:inline">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE" >
                                    <button id='deleteAlbum' type="button" class="btn btn-outline-danger" ><a><i class="icon-trash-o"></i></a></button>
                                </form>
                            </div>
                        @endforeach
                        @if(count($albums)==0)
                            <p class="font-medium-3 text-muted text-xs-center" style="margin:150px">No Albums Yet</p>   
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
  
    <!-- Modal -->
    <div class="modal fade text-xs-left" id="addAlbum" tabindex="-1" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form class="form" method="POST" action="{{ route('albums.store') }}">
                    <div class="modal-body">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <h4 class="form-section">Add New Album</h4>
                            <div class="form-group">
                                <label for="name">Album name</label>
                                <input class="form-control " id="name" type="text" placeholder="Album Name"  name="name" required>
                            </div>

                            <div class="form-group">
                                <label for="year">Album Year</label>
                                <select class="form-control " id="year" placeholder="Album Year"  name="year" required>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                </form>                                    
            </div>
        </div>
    </div>
    <div class="modal fade text-xs-left" id="editAlbum" tabindex="-1" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <form class="form" method="POST" id="editAlbumForm" action="">
                    <input type="hidden" name="_method" value="PATCH" >
                    <div class="modal-body">
                        {{ csrf_field() }}
                        <div class="form-body">
                            <h4 class="form-section">Edit Album</h4>
                            <div class="form-group">
                                <label for="editname">Album name</label>
                                <input class="form-control " id="editname" type="text" placeholder="Album Name"  name="editname" required>
                            </div>

                            <div class="form-group">
                                <label for="edityear">Album Year</label>
                                <select class="form-control " id="edityear" placeholder="Album Year"  name="edityear" required>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                    </div>
                </form>                                    
            </div>
        </div>
    </div>
    
 @endsection

 @section('js')
    <script>
        $(document).ready(function(){
            var current = parseInt(new Date().getFullYear());
            var html;
            for(var i=0;i<10;i++){
                html = "<option id='"+(current-i)+"'>"+(current-i)+"</option>";
                $('#year').append(html);
                $('#edityear').append(html);
            }
        });

        function editAlbum(album){
            $('#editAlbumForm').attr('action',"{{ URL::to('/admin/albums/')}}"+"/"+album.id);
            $("input[name='editname']").val(album.name);
            $("select[name='edityear']").val(album.year);
            $('#editAlbum').modal('show');
        }
    </script>
 @endsection

resources/views/admin/albums/show.blade.php
@extends('layouts.admin')
@section('css')
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.css'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/default-skin/default-skin.min.css'>
    <link href="/admin-assets/dist/styles.imageuploader.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="/admin-assets/app-assets/css/pages/gallery.css">
    <link rel="stylesheet" type="text/css" href="/admin-assets/gallery/css/style.css">
@endsection

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Album Gallery #{{ $album->name }}</h2>
        </div>
        <div class="content-header-right breadcrumbs-right breadcrumbs-top col-md-6 col-xs-12">
            <div class="breadcrumb-wrapper col-xs-12">
                <ol class="breadcrumb">
                    <a class="btn btn-primary btn-min-width mr-1 mb-1 " href="{{ route('albums.index') }}">Back</a>
                </ol>
            </div>
        </div>
    </div>
    <div class="content-body">

        <!-- Image grid -->
        <section id="image-gallery" class="card">
            <div class="card-header">
                <h4 class="card-title">Image gallery</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div style="text-align:right">
                    <button type="button" class="btn btn-primary mt-1 mr-1 mb-1" data-toggle="modal" data-keyboard="false" data-backdrop="static" data-target="#uploadImagesModal">
                        Add Images
                    </button>

                </div>
                @if(count($album->album_images)==0)
                    <p class="font-medium-3 text-muted text-xs-center" style="margin:100px">No Images Yet</p>   
                @endif

                <div class="card-block my-gallery" itemscope itemtype="http://schema.org/ImageGallery">
                    <div class="row">
                        @foreach($album->album_images as $image)
                            <figure class="col-lg-3 col-md-6 col-xs-12" itemprop="associatedMedia"  itemscope itemtype="http://schema.org/ImageObject" >
                                <a href="{{ route('optimize', ['gallery',$image->image,480,360]) }}" itemprop="contentUrl" data-size="480x360">
                                    <img class="img-thumbnail img-fluid" src="{{ route('optimize', ['gallery',$image->image,172,172]) }}" itemprop="thumbnail" alt="Image {{$loop->iteration}}" />
                                </a>
                                <form action="{{ route('albums.deleteImage',[$album->id,$image->id]) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE" >
                                    <button id='deletePhoto' type="button" style="background-color: Transparent;border: none;outline:none;position: absolute;top: -10px;right: 0px;" ><a><i class="icon-cross"></i></a></button>
                                </form>
                            </figure> 
                        @endforeach
                    </div>
                </div>

                <!-- Root element of PhotoSwipe. Must have class pswp. -->
                <div class="pswp" tabindex="-1" role="dialog" aria-hidden="true">

                    <!-- Background of PhotoSwipe. 
                        It's a separate element, as animating opacity is faster than rgba(). -->
                    <div class="pswp__bg"></div>

                    <!-- Slides wrapper with overflow:hidden. -->
                    <div class="pswp__scroll-wrap">

                        <!-- Container that holds slides. PhotoSwipe keeps only 3 slides in DOM to save memory. -->
                        <!-- don't modify these 3 pswp__item elements, data is added later on. -->
                        <div class="pswp__container">
                            <div class="pswp__item"></div>
                            <div class="pswp__item"></div>
                            <div class="pswp__item"></div>
                        </div>

                        <!-- Default (PhotoSwipeUI_Default) interface on top of sliding area. Can be changed. -->
                        <div class="pswp__ui pswp__ui--hidden">

                            <div class="pswp__top-bar">

                                <!--  Controls are self-explanatory. Order can be changed. -->

                                <div class="pswp__counter"></div>

                                <button class="pswp__button pswp__button--close" title="Close (Esc)"></button>

                                <button class="pswp__button pswp__button--share" title="Share"></button>

                                <button class="pswp__button pswp__button--fs" title="Toggle fullscreen"></button>

                                <button class="pswp__button pswp__button--zoom" title="Zoom in/out"></button>

                                <!-- Preloader demo https://codepen.io/dimsemenov/pen/yyBWoR -->
                                <!-- element will get class pswp__preloader--active when preloader is running -->
                                <div class="pswp__preloader">
                                    <div class="pswp__preloader__icn">
                                    <div class="pswp__preloader__cut">
                                        <div class="pswp__preloader__donut"></div>
                                    </div>
                                    </div>
                                </div>
                            </div>

                            <div class="pswp__share-modal pswp__share-modal--hidden pswp__single-tap">
                                <div class="pswp__share-tooltip"></div> 
                            </div>

                            <button class="pswp__button pswp__button--arrow--left" title="Previous (arrow left)">
                            </button>

                            <button class="pswp__button pswp__button--arrow--right" title="Next (arrow right)">
                            </button>

                            <div class="pswp__caption">
                                <div class="pswp__caption__center"></div>
                            </div>

                        </div>

                        </div>

                </div>
            </div>
        </section>
        <!--/ Image grid -->
    </div>
    <!-- Modal -->
    <div class="modal fade text-xs-left" id="uploadImagesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" style="min-height:500px;min-width:500px;">
        <div class="modal-dialog" role="document">

            <div style="text-align:right">             
                <button id="cross"  type="button" class="btn btn-outline-secondary" data-dismiss="modal" style="background-color: #185284;color: #fff;">&times;</button>
            </div>            
            <div class=" uploader__box js-uploader__box l-center-box">
                <form class="form" enctype="multipart/form-data" method="POST" action="{{ route('albums.addImages',$album->id) }}">
                       
                    {{ csrf_field() }}
                    <div class="form-body">
                        <div class="uploader__contents">
                            <label class="button button--secondary" for="fileinput">Select Files</label>
                            <input id="fileinput" class="uploader__file-input" type="file" multiple value="Select Files">
                        </div>
                        <button class="button button--big-bottom" type="submit">Upload Selected Files</button>
                    </div>

                </form> 
            </div>
        </div>
    </div>
 @endsection

 @section('js')
    <script src='https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/photoswipe/4.1.1/photoswipe-ui-default.min.js'></script>

    <script  src="/admin-assets/gallery/js/index.js"></script>
    <script src="/admin-assets/dist/jquery.imageuploader.js"></script>
	<script>
		(function(){
            var options = {'ajaxUrl':"{{ route('albums.addImages',$album->id) }}"};
            $('.js-uploader__box').uploader(options);
        }());
    </script>
 @endsection