routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/about-us', 'HomeController@about');
Route::get('/facilities', 'HomeController@facilities');
Route::get('/blogs','HomeController@blog');
Route::get('/contact','HomeController@contact');
Route::get('/albums/{slug}', 'HomeController@albumImages');

Route::get('/albums', 'HomeController@albums');
Route::get('/albums/{slug}', 'HomeController@albumImages');




Route::prefix('admin')->group(function(){
    Route::get('/login','Admin\Auth\LoginController@showLoginForm')->name('admin_login');
	Route::post('/login','Admin\Auth\LoginController@login');
	Route::post('/logout','Admin\Auth\LoginController@logout')->name('admin_logout');
	Route::post('/password/email','Admin\Auth\ForgotPasswordController@sendResetLinkEmail')->name('admin_password.email');
	Route::post('/password/reset','Admin\Auth\ResetPasswordController@reset');
	Route::get('/password/reset','Admin\Auth\ForgotPasswordController@showLinkRequestForm')->name('admin_password.request');
	Route::get('/password/reset/{token}','Admin\Auth\ResetPasswordController@showResetForm')->name('admin_password.reset');
    
    Route::get('profile','Admin\ProfileController@index')->name('profile');
    Route::post('profile/changePassword','Admin\ProfileController@changePassword')->name('profile.changePassword');
    Route::post('profile/changeName','Admin\ProfileController@updateName')->name('profile.updateName');

    Route::post('albums/{id}/addImages','Admin\AlbumController@addImages')->name('albums.addImages');
    Route::delete('albums/{album_id}/deleteImage/{image_id}','Admin\AlbumController@deleteImage')->name('albums.deleteImage');
    Route::resource('albums', 'Admin\AlbumController',['except' => ['create','edit']]);

    Route::get('settings','Admin\SettingsController@index')->name('admin.settings');
    Route::post('settings/addImage','Admin\SettingsController@addImage')->name('admin.settings.addImage');
    Route::delete('settings/removeImage/{id}','Admin\SettingsController@removeImage')->name('admin.settings.removeImage');
    Route::post('settings/contactUpdate','Admin\SettingsController@contactUpdate')->name('admin.settings.contactUpdate');
    Route::post('settings/aboutUpdate','Admin\SettingsController@aboutUpdate')->name('admin.settings.aboutUpdate');
    
    Route::get('newsletter','Admin\NewsletterController@newsletter')->name('newsletter');
    Route::post('newsletter/send','Admin\NewsletterController@newsletterSend')->name('newsletterSend');

    Route::get('contact-us-messages/unseen','Admin\ContactUsMessageController@unseenMsg')->name('contact-us-messages.unseen');    
    Route::get('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@reply')->name('contact-us-messages.reply');
    Route::post('contact-us-messages/reply/{id}','Admin\ContactUsMessageController@replySend')->name('contact-us-messages.replySend');
    Route::resource('contact-us-messages', 'Admin\ContactUsMessageController',['only' => ['show','destroy','index']]);
    Route::get('getUnseenMsgCount','Admin\ContactUsMessageController@getUnseenMsgCount')->name('getUnseenMsgCount');
    Route::get('getUnseenMsg','Admin\ContactUsMessageController@getUnseenMsg')->name('getUnseenMsg');

    Route::resource('testimonials', 'Admin\TestimonialController',['except' => ['create','show']]);

    Route::get('dashboard','Admin\AdminController@index')->name('admin_dashboard');
    Route::post('test','Admin\AdminController@test')->name('test');

    Route::get('/','Admin\AdminController@index');
});

Route::get('/asset/{source}/{img}/{h}/{w}',function($source,$img, $h, $w){
    $ext = explode(".",$img);
    $ext = end($ext);
    $source = str_replace('*','/',$source);
    return \Image::make(public_path("/".$source."/".$img))->resize($h, $w)->response($ext);
})->name('optimize');

resources/views/admin/dashboard.blade.php
@extends('layouts.admin')

@section('body')
    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Dashboard</h2>
        </div>
        <div class="text-xs-right">
            <button class="btn btn-primary btn-min-width mr-2 mb-1" data-toggle="modal" data-target="#addAlbum">Add new</button>
        </div>
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <div class="row">
                        <form action="{{ route('test') }}" method="POST">
                            {{ csrf_field() }}
                            <button id='delete' type="button" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
   </div>
@stop

@section('js')

@endsection

resources/views/admin/newsletter.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Create Newsletter</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <form class="form" method="POST" action="{{ route('newsletterSend') }}"  enctype="multipart/form-data">
                        {{ csrf_field() }}
                        <input name="image" type="file" id="upload" class="hidden" onchange="">

                        <div class="form-group">
                            <label for="subject">Subject</label>
                            <input type="text" class="form-control{{ $errors->has('subject') ? ' border-danger' : '' }}" id="subject" name="subject">
                            @if ($errors->has('subject'))
                                <div class="alert alert-danger no-border mb-2">
                                    <strong>{{ $errors->first('subject') }}</strong>
                                </div>
                            @endif
                        </div>

                        <div class="form-group">
                            <label for="attachment">Attachment</label>
                            <input type="file" class="form-control" id="attachment" name="attachment">
                        </div>

                        <div class="form-group">
                            <label for="message">Message <span style="color:red;font-size:25px;">*</span></label>
                            @if ($errors->has('message'))
                                <div class="alert alert-danger no-border mb-2">
                                    <strong>{{ $errors->first('message') }}</strong>
                                </div>
                            @endif
                            <textarea cols="50" rows="20" class="form-control{{ $errors->has('message') ? ' border-danger' : '' }}" id="message" name="message"></textarea>
                        </div>

                        <div class="form-actions right">
                            <button type="submit" class="btn btn-primary">
                                <i class="icon-check2"></i> Save
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

@section('js')
   <script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
   <script>
       tinymce.init({
           selector: "textarea#message",
           
           plugins: [
               "advlist autolink lists link image charmap print preview hr anchor pagebreak",
               "searchreplace wordcount visualblocks visualchars code",
               "insertdatetime media nonbreaking save table contextmenu directionality",
               "emoticons template paste textcolor colorpicker textpattern"
           ],
           toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image",
           toolbar2: "print preview | forecolor backcolor emoticons | template",
           image_advtab: true,
           file_picker_callback: function(callback, value, meta) {
           if (meta.filetype == 'image') {
               $('#upload').trigger('click');
               $('#upload').on('change', function() {
               var file = this.files[0];
               var reader = new FileReader();
               reader.onload = function(e) {
                   callback(e.target.result, {
                   alt: ''
                   });
               };
               reader.readAsDataURL(file);
               });
           }
           },
           templates: [
               {title: 'Newsletter1', description: 'Notice', url: "/templates/newsletter.html"}
             ]
       });
   </script>
  
@endsection

resources/views/admin/profile.blade.php
@extends('layouts.admin')

@section('css') 
    <link href="/admin-assets/bootstrap3-editable/css/bootstrap-editable.css" rel="stylesheet" type="text/css">
@endsection

@section('body')

    <div class="content-header row">
    </div>
    <div class="content-body">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Profile</h4>
                <a class="heading-elements-toggle"><i class="icon-ellipsis font-medium-3"></i></a>
                <div class="heading-elements">
                    <ul class="list-inline mb-0">
                        <li><a data-action="collapse"><i class="icon-minus4"></i></a></li>
                        <li><a data-action="expand"><i class="icon-expand2"></i></a></li>
                    </ul>
                </div>
            </div>
            <div class="card-body collapse in">
                <div class="card-block card-dashboard">
                    <button id="changePswd" class="btn btn-warning btn-min-width mr-1 mb-2">Change Password</button>                            
                    <br><br>
                    <strong>Username: </strong> <a id="admin_name" href="javascript:void(0);">{{ Auth::user()->name }}</a><br><br>
                    <strong>Email: </strong> {{ Auth::user()->email }}<br>
                    
                    <div style="height:174px"></div>
                    <!-- Modal -->
                    <div class="modal fade text-xs-left" id="changePasswordModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel5" aria-hidden="true" >
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form class="form" method="POST" action="{{ route('profile.changePassword') }}">
                                    <div class="modal-body">
                                        {{ csrf_field() }}
                                        <div class="form-body">
                                            <h4 class="form-section">Password Update</h4>
                                            @if (count($errors->changePassword)>0 )
                                                <div class="alert alert-dismissible fade in mb-2">
                                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                        <span aria-hidden="true" style="color:black">&times;</span>
                                                    </button>
                                                    <ul class="list-group">
                                                        @foreach ($errors->changePassword->all() as $error)
                                                        <li class="list-group-item list-group-item-danger">{{ $error }}</li>
                                                        @endforeach
                                                    </ul>
                                                </div>	
                                            @endif
                                            <div class="form-group">
                                                <label for="oldPasswrd">Old Password</label>
                                                <input class="form-control " id="oldPasswrd" type="password" placeholder="Old Password"  name="oldPassword" required>
                                            
                                            </div>

                                            <div class="form-group">
                                                <label for="passwrd">New Password</label>
                                                <input class="form-control " id="passwrd" type="password" placeholder="New Password"  name="password" required>
                                                
                                            </div>

                                            <div class="form-group">
                                                <label for="passwrd-confirm">Confirm New Password</label>
                                                <input class="form-control " id="passwrd-confirm" type="password" placeholder="Confirm New Password"  name="password_confirmation" required>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn grey btn-outline-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-outline-primary">Save changes</button>
                                    </div>
                                </form>                                    
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
@endsection

@section('js')

    <script>
        if({{ count($errors->changePassword)}} > 0){
            $('#changePasswordModal').modal('show');
        }
        $('#changePswd').click(function(){
            $('#changePasswordModal').modal('show');
        });
    </script>
    <script src="/admin-assets/bootstrap3-editable/js/bootstrap-editable.js"></script>
	<script>

        $.fn.editable.defaults.mode = 'inline';
        $('#admin_name').editable({
            type: 'text',
            url: '{{route("profile.updateName")}}',
            title: 'Edit Name',
            send: 'always',
            validate: function(value) {
                if($.trim(value) == '') {
                    return 'This field is required';
                }
            },
            success:function(value){
                $('#adminName').text(value);
            }
        });
    </script>
   
@endsection

resources/views/admin/testimonials.blade.php
@extends('layouts.admin')

@section('body')

    <div class="content-header row">
        <div class="content-header-left col-md-6 col-xs-12 mb-1">
            <h2 class="content-header-title">Testimonials</h2>
        </div>
    </div>
    <div class="row match-height">
        <div class="col-xl-4 col-md-6 col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="card-block">
                    @if($state == 'Add')
                        <form class="form" method="POST" action="{{ route('testimonials.store') }}"  enctype="multipart/form-data">
                    @else
                        <form class="form" method="POST" action="{{ route('testimonials.update',$testimonial_->id) }}"  enctype="multipart/form-data">                            
                        <input type="hidden" name="_method" value="PATCH" >
                    @endif
                            {{ csrf_field() }}
                            
                            <div class="form-group">
                                <label for="name"><strong>Name:</strong></label>
                                @if ($errors->has('name'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="name" class="form-control" name="name" value="{{ $testimonial_->name }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="profession"><strong>Profession:</strong></label>
                                @if ($errors->has('profession'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('profession') }}</strong>
                                    </div>
                                @endif
                                <input type="text" id="profession" class="form-control" name="profession" value="{{ $testimonial_->profession }}" required/>
                            </div>

                            <div class="form-group">
                                <label for="photo"><strong>{{ $state=='Add'?'':'Current ' }}Image <span class="text-muted">(Optional)</span>: </strong></label> {{ $testimonial_->photo }}
                                @if ($errors->has('photo'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('photo') }}</strong>
                                    </div>
                                @endif
                                <input type="file" id="photo" class="form-control" name="photo"/>
                            </div>
                            <div class="form-group">
                                <label><strong>New Testimonial:</strong></label>
                                @if ($errors->has('content'))
                                    <div class="alert alert-danger no-border mb-2">
                                        <strong>{{ $errors->first('content') }}</strong>
                                    </div>
                                @endif
                            
                                <textarea class="form-control" rows='6' id="content" name="content" required>{{ $testimonial_->content }}</textarea>

                            </div>
                            <div class="form-actions right">
                                <button type="submit" class="btn btn-primary">
                                    <i class="icon-check2"></i> {{ $state=="Add"?"Add New":"Save" }}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @foreach($testimonials as $testimonial)
            <div class="col-xl-4 col-md-6 col-sm-12">
                <div class="card">
                    <div class="card-body">
                        <div class="card-block">
                            <h4 class="card-title">{{ $testimonial->name }}</h4>
                            <h6 class="card-subtitle text-muted">{{ $testimonial->profession }}</h6>
                            @if($testimonial->photo)
                                <img class="img-fluid my-1" src="{{ route('optimize', ['landing_images',$testimonial->photo,290,290]) }}" alt="Card image cap">
                            @else
                                <img class="img-fluid my-1" src="{{ route('optimize', ['img','avatar.png',290,290]) }}" alt="{{ $testimonial->name }}"/>
                            @endif
                            <p class="card-text">{{ $testimonial->content }}</p>

                            <a href="{{ route('testimonials.edit',$testimonial->id) }}" class="btn btn-outline btn-warning">Edit</a>
                            
                            <form action="{{ route('testimonials.destroy',$testimonial->id) }}" style="display:inline" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE" >
                                <button id='deleteTestimonial' type="button" class="btn btn-outline btn-danger">Delete</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection